name: Ubuntu VPS with Ngrok

on: [push, workflow_dispatch]  # Trigger on push or manual dispatch

jobs:
  setup-vps:
    runs-on: ubuntu-22.04  # Using Ubuntu 22.04

    steps:
    - name: Update and Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y openssh-server wget jq unzip

    - name: Configure SSH Access
      run: |
        # Enable root login
        echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
        echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
        sudo systemctl restart sshd
        # Set root password
        echo -e "Passxi23\nPassxi23" | sudo passwd root
        echo "Root user password has been set."

    - name: Download Ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        sudo mv ngrok /usr/local/bin/

    - name: Authenticate Ngrok
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
        ngrok authtoken $NGROK_AUTH_TOKEN

    - name: Start Ngrok for SSH
      run: |
        nohup ngrok tcp 22 &> ngrok.log &
        sleep 10 # Allow Ngrok to initialize
        cat ngrok.log

    - name: Fetch Ngrok Public Address
      run: |
        NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
        echo "Ngrok SSH URL: $NGROK_URL"
        echo $NGROK_URL > ngrok_ssh_url.txt

    - name: Upload Ngrok SSH URL as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ngrok-ssh-url
        path: ngrok_ssh_url.txt

    - name: Keep Workflow Running
      run: |
        echo "Ngrok tunnel is running. Use the SSH URL to connect."
        tail -f /dev/null  # Keeps the workflow active until manually stopped
